export const cars = [
   {
      id: 1,
      name: 'VOLVO S90',
      img: 'volvo.jpg',
      shipping: false,
      new: false,
      description: '2.0 T8 HYBRID INSCRIPTION AWD GEARTRONIC',
      year: '2019/2020',
      km: 18811,
      price: 289900,
      total: 0,
   },
   {
      id: 2,
      name: 'NISSAN LEAF',
      img: 'leaf.jpg',
      shipping: false,
      new: false,
      description: 'B12P 40 ELÉTRICO',
      year: '2019/2020',
      km: 24527,
      price: 175950,
      total: 0,
   },
   {
      id: 3,
      name: 'PORSCHE CAYENNE',
      img: 'porsche.jpg',
      shipping: false,
      new: false,
      description: '3.0 V6 E-HYBRID AWD TIPTRONIC S',
      year: '2020/2020',
      km: 19710,
      price: 619900,
      total: 0,
   },
   {
      id: 4,
      name: 'MERCEDES-BENZ GLE 350',
      img: 'mbenz350.jpg',
      shipping: false,
      new: false,
      description: '3.0 V6 BLUETEC DIESEL SPORT 4MATIC 9G-TRONIC',
      year: '2015/2016',
      km: 64700,
      price: 268900,
      total: 0,
   },
   {
      id: 5,
      name: 'AUDI Q7',
      img: 'audiq7.jpg',
      shipping: false,
      new: false,
      description: '3.0 V6 TDI DIESEL PERFORMANCE TIPTRONIC',
      year: '2019/2019',
      km: 32000,
      price: 384900,
      total: 0,
   },
   {
      id: 6,
      name: 'TESLA MODEL Y',
      img: 'tesla.jpg',
      shipping: true,
      new: true,
      description: 'P100D PERFORMANCE AWD ELÉTRICO',
      year: '2022/2022',
      km: 0,
      price: 749890,
      total: 0,
   },
   {
      id: 7,
      name: 'JEEP COMMANDER',
      img: 'jeep.jpg',
      shipping: true,
      new: true,
      description: '2.0 TD380 TURBO DIESEL OVERLAND AT9',
      year: '2022/2022',
      km: 0,
      price: 287900,
      total: 0,
   },
   {
      id: 8,
      name: 'HONDA HR-V',
      img: 'hrv.jpg',
      shipping: true,
      new: true,
      description: '1.5 DI I-VTEC FLEX EX CVT',
      year: '2022/2023',
      km: 0,
      price: 164900,
      total: 0,
   },
   {
      id: 9,
      name: 'AUDI Q3',
      img: 'audiq3.jpg',
      shipping: true,
      new: true,
      description: '2.0 40 TFSI GASOLINA PERFORMANCE QUATTRO TIPTRONIC',
      year: '2022/2022',
      km: 0,
      price: 304000,
      total: 0,
   },
   {
      id: 10,
      name: 'RAM 3500',
      img: 'ram3500.jpg',
      shipping: true,
      new: true,
      description: '6,7 I6 TURBO DIESEL LARAMIE CD 4X4 AUTOMÁTICO',
      year: '2022/2022',
      km: 0,
      price: 539000,
      total: 0,
   }
]